services:
  dockcheck:
    container_name: dockcheck
    hostname: dockerHostXYZ # The name that will be used in notifications
    # build: . # To build locally from the cloned/edited repo - good for testing
    image: mag37/dockcheck:latest
    restart: unless-stopped
    environment:
      # Set up cron schedules and corresponding dockcheck options, examples below
      CRON_SCHEDULE: "0 */3 * * *" # Run every three hours
      DOCKCHECK_ARGS: "-mniI -x 10 -e container1" # Send notification + extra options
      CRON_SCHEDULE_1: "30 1 * * *" # Run nightly at 1:30
      DOCKCHECK_ARGS_1: "-milap" # Send notification, update labeled containers, prune 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock # Beware - full access
      - ./dockcheck.config:/app/dockcheck.config # Define your notifications and settings
      # Volume mappings to your Docker project directories, can be multiple paths
      # Has to match 1:1 outside on host and inside the container
      - /path/to/projects/docker:/path/to/projects/docker:ro  
      # Optional volume to enable displaying releasenote urls, 
      # can alternatively reference the `./notify_templates/urls.list` 
      # - ./urls.list/:/app/urls.list 
