services:
  dockcheck:
    image: dockcheck:latest
    restart: unless-stopped
    environment:
      CRON_SCHEDULE: "0 * * * *"
      DOCKCHECK_ARGS: "-mniI -x 10"
      CRON_SCHEDULE_1: "30 1 * * *"
      DOCKCHECK_ARGS_1: "-milap -x 1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockcheck.config:/app/dockcheck.config
      - /path/to/projects/docker:/path/to/projects/docker:ro
